language: python
python:
  - 3.5
  - 3.6

install: pip install -U tox-travis
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sharktamer
  password:
    secure: fh0O42FcuQ+TQxyGVcN2X43RjZ5FjQbkmP8Xl/ciuXa/LxWb3sBry+/o5VVFgevhsMIfmiN7uy9EpU3ZQNFNoXgyVwKAl12OIHPDmJ+aUchA/vT65XzjGcu+jh9m9igMRVaoYWlC+aHm1X6a9SAizYgRXV2sETuzuCYVAvNe6cKUbRVYmMU1NTxWd2N+ZTFUritKmLLu2+fpr0Oivew5NHSw3BielK+bX5hQpOJvMyqcbzxDayd3EFBsnKGTYH38srTBVI0W74EhCzNAhFFUuyajoGy85pcUfL+eYzzh4OCIABJRlJWXwQHEZ4Fw2i8ZNHrTj4A8LuhItMVIeaOxjUFfgkYFAGg1s34lFAxNT8UsufK63YzgF8q7IZpDZd1JLmrg7sML1L6u1zKEh6UU6+RlvkyRBR30BO4QglRKd/S+S/ky3sJjn5f+i+/jujkQgwC9fRV/yLIATI83CEt9Np4e7/EZpUTLgkY4z0ReS4SOiwSfzwmlg1KJtlhVzx+Z2Fjvx0cgh8g1fZgSfW4tkTxo+fbdNBiPaOJkLPL89E4rVjYJoDIoJeF88hFlY44dLu4LcsjvY+cBRmFY47m64QLYE8LxepKIDol+QUe6Po1UTy7YmVfuvntf94e8shcIWCaxh73KrbbNozYX/vYRgKhEx0WQIuQdl4D99q9jZXY=
  on:
    tags: true
    repo: shanedabes-sopel/sopel-checkiday
    python: 3.6
